package mypack;
// Generated Sep 20, 2020 8:39:12 PM by Hibernate Tools 5.4.18.Final

/**
 * Student1 generated by hbm2java
 */
public class Student1 implements java.io.Serializable {

	private Integer rollno;
	private String address;
	private int age;
	private String name;

	public Student1() {
	}

	public Student1(int age) {
		this.age = age;
	}

	public Student1(String address, int age, String name) {
		this.address = address;
		this.age = age;
		this.name = name;
	}

	public Integer getRollno() {
		return this.rollno;
	}

	public void setRollno(Integer rollno) {
		this.rollno = rollno;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
